Update patch set 7
Patch Set 7:

> Patch Set 7: -Code-Review
> 
> Doesn't seem to compile.
> 
> error: resource style/Theme.AppCompat.DayNight.NoActionBar (aka com.android.stk:style/Theme.AppCompat.DayNight.NoActionBar) not found.
> error: failed processing manifest.

Sorry for that. I do not see the same error on Android 10 based software. It was removed by the recent change?

Patch-set: 7
Reviewer: Gerrit User 1163305 <1163305@85c56323-6fa9-3386-8a01-6480fb634889>